add-parser
neonet1984/ConverterYamlToProperties pull request #1
Opened 2018-02-20 20:22 UTC by neonet1984

2018-02-21 23:05 UTC, asdfv requested changes
Need work

2018-02-21 23:05 UTC, asdfv commented on src/main/java/Main.java
> +    private static Properties properties;
Зачем все сделал static?
Инициализацию можно сделать сразу в полях класса

2018-02-21 23:05 UTC, asdfv commented on src/main/java/Main.java
> +        writeFile.writeFile(propertiesList, outputFile);
writeFile.writeFile - масло маслянное
fileWriter.write - и то лучше

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/ReadFile.java
> +        this.reader = new BufferedReader(new FileReader(patch));
Зачем опять this?? Ты его везде пишешь, почитай для чего он нужен и когда и завтра мне расскажешь

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/ReadFile.java
> +        while ((line = reader.readLine()) != null) {
Второй раз повторяю, такие вещи надо делать стримом

2018-02-21 23:05 UTC, asdfv commented on src/main/java/Main.java
> +    private static final String path = "app.properties";
Константы в верхнем регистре пишем

2018-02-21 23:05 UTC, asdfv commented on src/main/java/Main.java
> +            LOG.error(e.getMessage());
В логе напиши что за ошибка, а потом только выводи месседж

2018-02-21 23:05 UTC, asdfv commented on src/main/java/Main.java
> +        LOG.info("Start parsing");
Парсинг начинается в 34 строке если что. И я говорил сделать вывод в конце сколько мс занял парсинг

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/ReadFile.java
> +    private static final Logger LOG = LoggerFactory.getLogger(ReadFile.class);
Давай логгер писать log, это не обязательно, но у нас так на проекте, сразу привыкай

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/ReadFile.java
> +    private List<String> yamlFile;
Некорректное название, я так понимаю ты хранишь тут лист строк из файла, а назвал переменную файлом. Назови yamlLines хотя бы

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/ReadFile.java
> +    public ReadFile(String path) {
Название не о чем и класс не понятный. Сделай интерфейс IReader с методом read(String path), заимплементь его в YamlReader в котором опиши метод read для ямла

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/ReadFile.java
> +        yamlFile = new ArrayList<>();
Эта переменная вообще не нужна. перепиши метод readYaml() что бы от нее избавится

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/ReadFile.java
> +            yamlFile = stream
Тут пиши сразу return stream
                                        .filter ... и т.д.

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/ReadFile.java
> +                    .filter(line -> !line.isEmpty() && !line.matches("^[#;].*") )
Условие фильтра вынеси в предикейт

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/WriteFile.java
> +public class WriteFile {
То же самое, что и выше, интерфейс IWriter, от него yamlWriter, метод write(String path)

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/WriteFile.java
> +            for (StringBuilder propertiesConfiguration : prop) {
Используй везде prop.foreach() - это современнее

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/WriteFile.java
> +            LOG.error(e.getMessage());
Логгер без коментария

2018-02-21 23:05 UTC, asdfv commented on src/main/java/model/YamlModel.java
> +public class YamlModel {
Все что в пакете модел - понятно, что модел, в названии класса можно опустить, просто Yaml

2018-02-21 23:05 UTC, asdfv commented on src/main/java/file/ReadFile.java
> +
Строку не надо пропускать

2018-02-21 23:05 UTC, asdfv commented on src/main/java/parser/AuxiliaryFuntionalParsing.java
> +public class AuxiliaryFuntionalParsing {
Я так понимаю это какой-то утильный вспомогательный класс?
Сделай для него пакет utils, сделай его static и методы его static и просто используй, не надо от него наследоваться. И название дай нормальное.

2018-02-21 23:05 UTC, asdfv commented on src/main/java/parser/AuxiliaryFuntionalParsing.java
> +            if (symbol == ' ') countSpace++;
Блок if всегда оборачиваем {} - такой codeStyle, else тоже

2018-02-21 23:05 UTC, asdfv commented on src/main/java/parser/Parser.java
> +
Поработай над названиями методов и переменных, тут какая-то дичь происходит и из названий ничего не понять

2018-02-21 23:05 UTC, asdfv commented on src/main/resources/logback.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Не вижу тут логирования в файл о котором говорили

2018-02-21 23:05 UTC, asdfv commented on src/test/java/ParserTest.java
> +        Assert.assertTrue(resultParser.equals(trueResult));
Не resultParser и trueResult, а actual и expected

2018-02-22 22:05 UTC, asdfv requested changes
Не понравился твой readme файл.
Интерфейсы кладут в пакет Service, в нем пакет impl - в котором имплементации лежат

2018-02-22 22:05 UTC, asdfv commented on src/main/java/Main.java
> +public class Main {
Где javadoc?

2018-02-22 22:05 UTC, asdfv commented on src/main/java/Main.java
> +    public static void main(String[] args) {
javadoc

2018-02-22 22:05 UTC, asdfv commented on src/main/java/Main.java
> +    private static final Logger Log = LoggerFactory.getLogger(Main.class);
Не Log, а log.

2018-02-22 22:05 UTC, asdfv commented on src/main/java/file/IWriter.java
> +    void write(List<T> PropertiesLines);
Опять переменная с большой буквы? Изучи naming convention java

2018-02-22 22:05 UTC, asdfv commented on src/main/java/file/PropertiesWriter.java
> +    public PropertiesWriter(String path) {
javadoc

2018-02-22 22:05 UTC, asdfv commented on src/main/java/file/PropertiesWriter.java
> +     * @param propertiesLines
propertiesLines - что это такое?

2018-02-22 22:05 UTC, asdfv commented on src/main/java/file/PropertiesWriter.java
> +        propertiesLines.forEach(
Слей 32 и 33 строки в одну

2018-02-22 22:05 UTC, asdfv commented on src/main/java/file/YamlReader.java
> +        Predicate<String> predicate = line -> !line.isEmpty() && !line.matches("^[#;].*");
predicate - плохое название, не описывает суть происходящего

2018-02-22 22:05 UTC, asdfv commented on src/main/java/file/YamlReader.java
> +        return null;
Возвращая тут null ты вынуждаешь выше делать проверку на null, которой у тебя скорее всего нету. Используй Collections.emptyList() вместо null - это праивльно

2018-02-22 22:05 UTC, asdfv commented on src/main/java/parser/Parser.java
> +    private List<StringBuilder> properties = new ArrayList<>();
Можно сделать эту переменную локальной?

2018-02-22 22:05 UTC, asdfv commented on src/main/java/parser/Parser.java
> +public class Parser {
Сложный для чтения код

2018-02-22 22:05 UTC, asdfv commented on src/main/java/parser/utils/UtilsParsing.java
> +public class UtilsParsing {
ParsingUtils уже тогда

2018-02-22 22:05 UTC, asdfv commented on src/main/java/parser/utils/UtilsParsing.java
> +     * @param yamlLine
yamlLine - что это?

2018-02-22 22:05 UTC, asdfv commented on src/main/java/parser/utils/UtilsParsing.java
> +        return (countYamlAttribure > 1);
1 скобки не нужны
2 объедини 16 и 17 строку

2018-02-22 22:05 UTC, asdfv commented on src/main/java/parser/utils/UtilsParsing.java
> +     * @param yamlLine
yamlLine ?

2018-02-22 22:05 UTC, asdfv commented on src/main/java/parser/utils/UtilsParsing.java
> +     * @param yamlLine
yamlLine? Описывай каждую переменную, раз уж вписал ее в javadoc

2018-02-22 22:05 UTC, asdfv commented on src/main/java/parser/utils/UtilsParsing.java
> +
пропуск лишний

2018-02-22 22:05 UTC, asdfv commented on src/main/java/parser/utils/UtilsParsing.java
> +     * @param propertiesLine
Опиши param

2018-02-22 22:05 UTC, asdfv commented on src/test/java/ParserTest.java
> +public class ParserTest {
А в тестах кто будет javadoc делать?

2018-02-22 22:05 UTC, asdfv commented on src/test/java/ParserTest.java
> +    public void Test() {
javadoc

2018-02-26 09:26 UTC, asdfv approved these changes

2018-02-26 12:53 UTC, pasha-remba commented on dependency-reduced-pom.xml
> +  <artifactId>Converter</artifactId>
Проект называется ConverterYamlToProperties, а по факту Converter

2018-02-26 12:53 UTC, pasha-remba commented on dependency-reduced-pom.xml
> +  </build>
Есть properties. Все версии выносишь в properties, чтобы я мог в одном месте поменять версию на любою либу.

2018-02-26 12:53 UTC, pasha-remba commented on src/test/java/ParserTest.java
> +
Удалить

2018-02-26 12:53 UTC, pasha-remba commented on pom.xml
> +                    <finalName>Converter</finalName>
Какое имя проекта?

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/Main.java
> +    private static final String PATH = "app.properties";
Path  мне кажется это неверное название

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/Main.java
> +        final String inputFile = properties.getProperty("input.file");
input.file
output.file
app.properties
Возможно создать class с константами?

2018-02-26 12:53 UTC, pasha-remba commented on pom.xml
> +    <dependencies>
Есть properties. Все версии выносишь в properties, чтобы я мог в одном месте поменять версию на любою либу.

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/Exeption/ValidatorExeption.java
> +    private final static String MESSAGE = "Invalid yaml file format";
Наверное лучше в класс с константами для сообщий об ошибке проверки валидации, т.к. возможно в будущем добавится еще какой-нибудь конвертер. Тут идет привязка к конкретике, больше абстракции

2018-02-26 12:53 UTC, pasha-remba commented on src/main/resources/logback.xml
> +    <root level="info">
Зачем дублирование

2018-02-26 12:53 UTC, pasha-remba commented on src/test/java/ParserTest.java
> +        Assert.assertTrue(actual.equals(expected));
Чем плохо assertEquals

2018-02-26 12:53 UTC, pasha-remba commented on src/test/java/ParserTest.java
> +    private List<String> expectedData = new ArrayList<>();
Зачем выносить на уровне класса?

2018-02-26 12:53 UTC, pasha-remba commented on src/test/java/ParserTest.java
> +        inputData = getInputData();
Не совсем понятно 
Тут ты сетаешь 
```
private List<String> getInputData() {
inputData.add("people:");
inputData.add("  personaldata:");
inputData.add("      name: \"Evgeny\"");
inputData.add("      age: \"20\"");
return inputData;
}
```
А тут еще раз 
`inputData = getInputData();`

2018-02-26 12:53 UTC, pasha-remba commented on src/test/java/ParserTest.java
> +        inputData.add("people:");
Возможно тут лучше локальный лист завести и потом в конструкторе сетать в глобальный лист.
В в before init производится если ты значение используешь в нескольких методах. Для одного метода не вижу смысла в before методе.

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlValidator.java
> +                .count() == 0;
Попробуй использовать NumberUtils.INTEGER_ZERO

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlValidator.java
> +                .count() == 0;
Вынеси в метод и дай имя методу говорящее о том, что тут происходит
`UtilsParsing.getCountSpace(yamlLine) % 4 != 0` 

Можешь даже наверное в класс UtilsParsing вынести эту проверку и дать универсальное имя метода.
И избався от
`Predicate<String> predicateForFilter = yamlLine -> UtilsParsing.getCountSpace(yamlLine) % 4 != 0;`
Сразу пиши в filter и используй статическую  ссылку на метод. Привер Person::getName()

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlValidator.java
> +        try {
if (!isVerificationYamlList(yamlLines)){
    log.error("Not a valid file", e);
}

+ может лучше просто один метод и сразу в стриме проверять это условие?

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlValidator.java
> +     *
Добавить описание ко входным и выходным параметрам для всех комментарий к методу

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlValidator.java
> + * The YamlValidator class is used to check the yaml lines, on correctness
плиз добавь 

> @link YamlValidator

чтобы была как ссылка по которой я мог бы перейти к классу

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlValidator.java
> +public class YamlValidator {
Заведи может интерфейс в котором есть один метод и от которого сможем imlemented и реализовывать свой валидатор для любого формата файла

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlFormator.java
> +public class YamlFormator {
Заведи может интерфейс в котором есть один метод и от которого сможем imlemented и реализовывать свой форматор

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/Main.java
> +            properties.load(new FileInputStream(PATH));
Не заметил закрытие ресурсов

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/Main.java
> +        log.info("End parsing");
Можно в одну строку  
```
log.info("End parsing");
log.info("Execution time of the program: " + (System.currentTimeMillis() - start) + " ms");
```

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/file/PropertiesWriter.java
> +    private static final Logger Log = LoggerFactory.getLogger(PropertiesWriter.class);
С большой только класс Log

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/file/IWriter.java
> +    void write(List<T> listLines);
Может лучше values вместо listLines

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/file/PropertiesWriter.java
> +                writer.append('\n').flush();
Используй может https://commons.apache.org/proper/commons-csv/jacoco/org.apache.commons.csv/Constants.java.html

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/file/YamlReader.java
> +    private static final Logger Log = LoggerFactory.getLogger(YamlReader.class);
Lоg c маленькой буквой

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/file/YamlReader.java
> +        Predicate<String> predicateForFilter = line -> !line.isEmpty() && !line.matches("^[#;].*");
используй isNotEmpty из CollectionUtils
вынеси в метод и назови метод так что тут творится !line.matches("^[#;].*")

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/Parser.java
> +
удалить лишний

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/UtilsParsing.java
> +
удалить 2 лишних отступа

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlFormator.java
> +            String yamlLineOne = yamlLines.get(index);
Разбей на подметоды и опиши что тут творится

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlFormator.java
> +        yamlLines = yamlList;
Просто lines yamlLines  yamlLines

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlFormator.java
> +        if (yamlLines.get(index).matches(".*>")) {
Поубирай  везде yaml  т.к. класс уже говорит с чем м работаем

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/YamlFormator.java
> +    private static void formatYamlList(int index) {
Напиши поподробнее что это такое за index

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/Parser.java
> +                .forEach(yaml -> propertiesKeyValue.append(yaml.getYamlKey() + "."));
https://commons.apache.org/proper/commons-csv/jacoco/org.apache.commons.csv/Constants.java.html

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/UtilsParsing.java
> +        int countYamlAttribure = yamlLine.trim().split(":").length;
https://commons.apache.org/proper/commons-csv/jacoco/org.apache.commons.csv/Constants.java.html

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/UtilsParsing.java
> +            if (symbol != ' ') {
https://commons.apache.org/proper/commons-csv/jacoco/org.apache.commons.csv/Constants.java.html

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/UtilsParsing.java
> +        return yamlLine.replace(":", "").trim();
https://commons.apache.org/proper/commons-csv/jacoco/org.apache.commons.csv/Constants.java.html

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/UtilsParsing.java
> +        return yamlLine.replace(":", "=").
https://commons.apache.org/proper/commons-csv/jacoco/org.apache.commons.csv/Constants.java.html

2018-02-26 12:53 UTC, pasha-remba commented on src/main/java/parser/UtilsParsing.java
> +                replace(" ", "").replace("\"", "");
https://commons.apache.org/proper/commons-csv/jacoco/org.apache.commons.csv/Constants.java.html

2018-02-26 17:33 UTC, merged